Updating limiter and renew funcs

diff --git a/module/udp b/module/udp
--- a/module/udp
+++ b/module/udp
@@ -342,6 +342,35 @@ renew_user() {
   sleep 3
 }
 
+#======== Renew Users ==========
+# Function to renew a user account
+renew_userr() {
+    read -p "Enter the username to renew: " username
+
+    if id "$username" &>/dev/null; then
+        user_date=$(chage -l "$username" | grep "Account expires" | awk -F': ' '{print $2}')
+        if [[ "$user_date" != "never" && $(date +%s) -gt $(date -d "$user_date" +%s) ]]; then
+            valid_date=false
+            while [ "$valid_date" = false ]; do
+                read -p "Enter the new expiration date for $username (YYYY-MM-DD): " new_date
+                # Check if the input date is valid (YYYY-MM-DD format)
+                if [[ "$new_date" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ && "$(date -d "$new_date" &>/dev/null; echo $?)" -eq 0 && "$(date -d "$new_date" +%s)" -gt "$(date +%s)" ]]; then
+                    valid_date=true
+                else
+                    echo "Invalid date format or date is in the past. Please use YYYY-MM-DD and provide a future date."
+                fi
+            done
+            chage -E "$new_date" "$username" >/dev/null 2>&1 # don't display output message'
+            passwd -u "$username" >/dev/null 2>&1  # Unlock the user's account
+            echo "Expiration date for $username has been renewed to $new_date and the account has been unlocked."
+        else
+            echo "The account for $username is not expired."
+        fi
+    else
+        echo "User $username does not exist."
+    fi
+}
+
 #======== remove client =========
 
 droppids() {
@@ -431,7 +460,11 @@ remove_user() {
   enter
 }
 
+USER_CONNECTIONS_FILE="/etc/UDPCustom/users_connections.txt"
 #========create client =============
+append_to_user_connections_file() {
+    echo "$1:$2" >> "$USER_CONNECTIONS_FILE"
+}
 
 add_user() {
   Fecha=$(date +%d-%m-%y-%R)
@@ -517,6 +550,7 @@ new_user() {
   done
 
   add_user "${nameuser}" "${userpass}" "${userdays}" "${limiteuser}"
+  append_to_user_connections_file "$1" "$4"
   clear
   msg -bar
   if [[ $msj = 0 ]]; then
@@ -976,7 +1010,7 @@ menu_udp_custom() {
   1) reset_udp_custom ;;
   2) new_user ;;
   3) remove_user ;;
-  4) renew_user ;;
+  4) renew_userr ;;
   5) block_user ;;
   6) detail_user ;;
   7) limiter ;;
